### ISSUE TITLE
Version 1.5.* is not working 

### ISSUE THREAD

**Issue by AlexKrupko** [captcha-com/angular1-captcha#4]
Hi all,

`init-script-include` request has been removed in 1.5 version and now library fails on captcha validation.

**Comment by botdetect-support** [comment]
@AlexKrupko 
We merged BotDetect client-side scripts into one in the recent release of BotDetect Captcha library. The ‘init-script-include’ request no longer exists.
Please upgrade BotDetect Captcha library to the latest version.
If you use the free version of BotDetect Captcha library, you can download it here: https://captcha.com/captcha-download.html.
If you own the paid BotDetect license, request the latest version here: https://captcha.com/shop/registration-form.html
